export type {
  PageType,
  NavigateProps,
  Service,
  Package,
  GalleryItem,
  Review,
  TimeSlot,
  BookingFormData,
  BookingRecord,
  BlockedSlot,
  QuoteFormData,
  ContactFormData,
  GHLContact,
  GHLOpportunity,
  CTAButtonProps,
} from '../types';